'use strict';
const $=id=>document.getElementById(id),KEY='nnotepad.v1';
let state={notes:[],active:null},available=true;
let contextId=null,contextOrigin=null;
function setStatus(message=''){$('status').textContent=message;$('status').hidden=!message;}
try{const raw=localStorage.getItem(KEY);if(raw){const parsed=JSON.parse(raw);if(!valid(parsed.notes))throw Error('Invalid saved data');state=parsed;}document.body.classList.toggle('dark',localStorage.getItem('nnotepad.theme')==='dark');}catch(e){available=false;setStatus(t('readFailed'));}
function valid(notes){return Array.isArray(notes)&&notes.every(n=>n&&typeof n.id==='string'&&typeof n.title==='string'&&typeof n.body==='string'&&typeof n.updated==='number'&&Number.isFinite(n.updated)&&(n.mode===undefined||['txt','md'].includes(n.mode))&&(n.view===undefined||['edit','split','preview'].includes(n.view)))&&new Set(notes.map(n=>n.id)).size===notes.length;}
function current(){return state.notes.find(n=>n.id===state.active)}
function persist(){if(!available){setStatus(t('storageUnavailable'));return;}try{localStorage.setItem(KEY,JSON.stringify(state));setStatus();}catch(e){setStatus(t('saveFailed'));}}
function create(){const n={id:crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random(),title:'',body:'',updated:Date.now(),mode:'txt',view:'split'};state.notes.unshift(n);state.active=n.id;persist();render();$('editor').focus();}
function list(){closeNoteMenu();const query=$('search').value.toLowerCase();$('notes').replaceChildren();for(const n of [...state.notes].sort((a,b)=>b.updated-a.updated)){if(!(n.title+'\n'+n.body).toLowerCase().includes(query))continue;const b=document.createElement('button');b.className='note'+(n.id===state.active?' active':'');b.dataset.noteId=n.id;b.setAttribute('aria-haspopup','menu');const heading=document.createElement('strong');heading.textContent=n.title||t('untitled');const p=document.createElement('span');p.textContent=n.body.replace(/\s+/g,' ').slice(0,65)||t('noContent');b.append(heading,p);b.onclick=()=>{state.active=n.id;persist();render();document.body.classList.remove('show')};b.oncontextmenu=e=>{e.preventDefault();openNoteMenu(n.id,b,e.clientX,e.clientY)};$('notes').append(b);}if(!$('notes').children.length){const p=document.createElement('p');p.textContent=t('noMatches');p.style.color='var(--muted)';$('notes').append(p);}}
function stats(){const text=$('editor').value,pos=$('editor').selectionStart,before=text.slice(0,pos);$('count').textContent=t('stats',{count:Array.from(text).length,lines:text.split('\n').length});$('cursor').textContent=t('cursor',{line:before.split('\n').length,column:Array.from(before.split('\n').at(-1)).length+1});}
function render(){const n=current();$('title').value=n.title;$('editor').value=n.body;$('date').textContent=t('edited',{date:new Date(n.updated).toLocaleString(UI_LOCALE)});list();stats();applyMode();}
function edit(){const n=current();n.title=$('title').value;n.body=$('editor').value;n.updated=Date.now();persist();list();stats();$('date').textContent=t('edited',{date:new Date(n.updated).toLocaleString(UI_LOCALE)});schedulePreview();}
function download(name,text,type){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function exportText(n=current()){const ext=n.mode==='md'?'.md':'.txt';download((n.title||t('untitled')).replace(/[<>:"/\\|?*\x00-\x1f]/g,'_')+ext,n.body,(n.mode==='md'?'text/markdown':'text/plain')+';charset=utf-8');}
function closeNoteMenu(restoreFocus=false){$('note-menu').hidden=true;contextId=null;if(restoreFocus&&contextOrigin&&contextOrigin.isConnected)contextOrigin.focus();contextOrigin=null;}
function openNoteMenu(id,origin,x,y){contextId=id;contextOrigin=origin;const n=state.notes.find(n=>n.id===id);$('export').textContent=n.mode==='md'?t('exportMd'):t('exportTxt');const menu=$('note-menu');menu.hidden=false;const rect=origin.getBoundingClientRect();if(!x&&!y){x=rect.left+12;y=rect.bottom;}menu.style.left=Math.max(8,Math.min(x,innerWidth-menu.offsetWidth-8))+'px';menu.style.top=Math.max(8,Math.min(y,innerHeight-menu.offsetHeight-8))+'px';$('export').focus();}
$('title').oninput=edit;$('editor').oninput=edit;$('editor').onclick=stats;$('editor').onkeyup=stats;$('search').oninput=list;$('new').onclick=create;
$('export').onclick=()=>{const n=state.notes.find(n=>n.id===contextId);closeNoteMenu(true);if(n)exportText(n)};
$('delete').onclick=()=>{const note=state.notes.find(n=>n.id===contextId);closeNoteMenu(true);if(!note||!confirm(t('deleteConfirm',{title:note.title||t('untitled')})))return;state.notes=state.notes.filter(n=>n.id!==note.id);if(!state.notes.length)create();else{if(state.active===note.id)state.active=state.notes[0].id;persist();render();}};
document.addEventListener('pointerdown',e=>{if(!$('note-menu').hidden&&!$('note-menu').contains(e.target))closeNoteMenu()});
window.addEventListener('resize',()=>closeNoteMenu());$('notes').addEventListener('scroll',()=>closeNoteMenu());
$('note-menu').addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();closeNoteMenu(true)}else if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();(document.activeElement===$('export')?$('delete'):$('export')).focus()}else if(e.key==='Tab')closeNoteMenu(true)});
$('import').onclick=()=>$('file').click();$('file').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const body=await f.text();create();current().title=f.name.replace(/\.[^.]+$/,'');current().body=body;current().mode=/\.(md|markdown)$/i.test(f.name)?'md':'txt';persist();render();}catch(err){alert(t('fileFailed'))}e.target.value='';};
$('backup').onclick=()=>download('NNotepad-backup-'+new Date().toISOString().slice(0,10)+'.json',JSON.stringify({version:1,notes:state.notes},null,2),'application/json');
$('restore').onclick=()=>$('json').click();$('json').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const data=JSON.parse(await f.text());if(data.version!==1||!valid(data.notes)||!data.notes.length)throw Error();if(!confirm(t('restoreConfirm')))return;state={notes:data.notes,active:data.notes[0].id};persist();render();}catch(err){alert(t('invalidBackup'))}finally{e.target.value='';}};
$('theme').onclick=()=>{document.body.classList.toggle('dark');try{localStorage.setItem('nnotepad.theme',document.body.classList.contains('dark')?'dark':'light')}catch(e){}};
function hideSidebar(){document.body.classList.add('sidebar-hidden');document.body.classList.remove('show');$('menu').setAttribute('aria-expanded','false');try{localStorage.setItem('nnotepad.sidebar','hidden')}catch(e){}}
function showSidebar(){document.body.classList.remove('sidebar-hidden');document.body.classList.add('show');$('menu').setAttribute('aria-expanded','true');try{localStorage.setItem('nnotepad.sidebar','shown')}catch(e){}}
$('hide-sidebar').onclick=hideSidebar;$('menu').onclick=showSidebar;
try{if(localStorage.getItem('nnotepad.sidebar')==='hidden')document.body.classList.add('sidebar-hidden')}catch(e){}
$('size').onchange=()=>{const size=$('size').value+'px';$('editor').style.fontSize=size;$('preview').style.fontSize=size};$('wrap').onchange=()=>$('editor').style.whiteSpace=$('wrap').checked?'pre-wrap':'pre';
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();exportText()}if(e.ctrlKey&&e.altKey&&e.key.toLowerCase()==='n'){e.preventDefault();create()}if(e.key==='Escape'){document.body.classList.remove('show');$('menu').setAttribute('aria-expanded','false')}});
window.addEventListener('storage',e=>{if(e.key===KEY&&e.newValue){setStatus(t('otherWindow'));available=false;}});
let previewTimer;
if(window.DOMPurify)DOMPurify.addHook('uponSanitizeAttribute',(node,data)=>{if(data.attrName==='href'&&!/^(https?:\/\/|mailto:|#)/i.test(data.attrValue))data.keepAttr=false;if(data.attrName==='src'&&!/^https?:\/\//i.test(data.attrValue))data.keepAttr=false;});
function applyMode(){const n=current(),md=n.mode==='md',view=n.view||'split';$('txt-mode').setAttribute('aria-pressed',!md);$('md-mode').setAttribute('aria-pressed',md);$('views').hidden=!md;$('workspace').className='workspace'+(md?' md view-'+view:'');$('workspace').querySelector('.editor-pane').hidden=md&&view==='preview';$('workspace').querySelector('.preview-pane').hidden=!md||view==='edit';for(const b of $('views').querySelectorAll('button'))b.setAttribute('aria-pressed',b.dataset.view===view);$('editor').placeholder=md?t('pasteMarkdown'):t('write');renderPreview();}
function setMode(mode){current().mode=mode;persist();applyMode();}
$('txt-mode').onclick=()=>setMode('txt');$('md-mode').onclick=()=>setMode('md');
for(const button of $('views').querySelectorAll('button'))button.onclick=()=>{current().view=button.dataset.view;persist();applyMode()};
function schedulePreview(){clearTimeout(previewTimer);if(current().mode==='md')previewTimer=setTimeout(renderPreview,120);}
const cleanOptions={ALLOWED_TAGS:['div','p','br','hr','h1','h2','h3','h4','h5','h6','strong','b','em','i','del','s','blockquote','ul','ol','li','pre','code','table','thead','tbody','tr','th','td','a','img','input','sup','sub','details','summary'],ALLOWED_ATTR:['href','src','alt','title','class','align','start','type','checked','disabled'],ALLOW_DATA_ATTR:false};
const converter=window.TurndownService&&window.turndownPluginGfm?new TurndownService({headingStyle:'atx',codeBlockStyle:'fenced',bulletListMarker:'-',emDelimiter:'*'}):null;
if(converter){converter.use(turndownPluginGfm.gfm);converter.addRule('strikethrough',{filter:['del','s','strike'],replacement:content=>'~~'+content+'~~'});converter.addRule('tableCellSafe',{filter:['th','td'],replacement:(content,node)=>{const first=node===node.parentNode.firstElementChild;return (first?'| ':' ')+content.trim().replace(/\n+/g,'<br>').replace(/(?<!\\)\|/g,'\\|')+' |'}});converter.keep(['sup','sub','details','summary']);}
function renderPreview(){clearTimeout(previewTimer);previewTimer=null;if(current().mode!=='md')return;const preview=$('preview'),text=current().body;if(!window.marked||!window.DOMPurify||!converter){preview.contentEditable='false';preview.textContent=t('missingComponents');return;}preview.contentEditable='true';if(!text.trim()){preview.replaceChildren();return;}try{preview.innerHTML=DOMPurify.sanitize(marked.parse(text,{gfm:true,breaks:true}),cleanOptions);for(const a of preview.querySelectorAll('a')){a.target='_blank';a.rel='noopener noreferrer';}for(const img of preview.querySelectorAll('img')){img.loading='lazy';img.referrerPolicy='no-referrer';}for(const input of preview.querySelectorAll('input')){if(input.type!=='checkbox'){input.remove();continue;}input.disabled=true;}}catch(e){preview.contentEditable='false';preview.textContent=t('renderFailed');}}
function savePreview(){if(current().mode!=='md'||!converter)return;clearTimeout(previewTimer);previewTimer=null;try{const clone=$('preview').cloneNode(true);for(const br of clone.querySelectorAll('pre br'))br.replaceWith(document.createTextNode('\n'));for(const input of clone.querySelectorAll('input[type=checkbox]'))input.toggleAttribute('checked',input.checked);const html=DOMPurify.sanitize(clone.innerHTML,cleanOptions);current().body=converter.turndown(html);current().updated=Date.now();$('editor').value=current().body;persist();list();stats();$('cursor').textContent=t('editingRich');$('date').textContent=t('edited',{date:new Date(current().updated).toLocaleString(UI_LOCALE)});}catch(e){setStatus(t('richSaveFailed'));}}
$('preview').addEventListener('input',savePreview);
$('preview').addEventListener('pointerdown',()=>{if(previewTimer)renderPreview()});
function selectionElement(){const selection=window.getSelection();const node=selection&&selection.anchorNode;return node&&(node.nodeType===1?node:node.parentElement);}
function insertPreview(text,html){const element=selectionElement();if(element&&element.closest('pre,code')||(!html&&!/[\n#*`|>\[\]]/.test(text))){document.execCommand('insertText',false,text);}else{const clean=DOMPurify.sanitize(html||marked.parse(text,{gfm:true,breaks:true}),cleanOptions);document.execCommand('insertHTML',false,clean);}savePreview();}
$('preview').addEventListener('paste',e=>{e.preventDefault();if(!e.clipboardData)return;insertPreview(e.clipboardData.getData('text/plain'),e.clipboardData.getData('text/html'));});
$('preview').addEventListener('drop',e=>{e.preventDefault()});
$('preview').addEventListener('keydown',e=>{if(e.isComposing)return;const element=selectionElement();if(element&&element.closest('pre')&&(e.key==='Enter'||e.key==='Tab')){e.preventDefault();document.execCommand('insertText',false,e.key==='Tab'?'    ':'\n');savePreview();}});
$('preview').addEventListener('click',e=>{const link=e.target.closest('a');if(link){e.preventDefault();if((e.ctrlKey||e.metaKey)&&link.href)window.open(link.href,'_blank','noopener,noreferrer');}});
if(!state.notes.length)create();else{if(!current())state.active=state.notes[0].id;render()}



