'use strict';
// Folders are browser-local groups, not directories on disk.
const folderText=(en,zh)=>document.documentElement.lang.startsWith('zh')?zh:en;
function folderId(){return crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random()}
function validFolders(folders){return Array.isArray(folders)&&folders.every(f=>f&&typeof f.id==='string'&&f.id.length>0&&!['all','unfiled'].includes(f.id)&&typeof f.name==='string'&&f.name.trim().length>0&&f.name.length<=60)&&new Set(folders.map(f=>f.id)).size===folders.length;}
function normalizeFolders(){if(!validFolders(state.folders))state.folders=[];const ids=new Set(state.folders.map(f=>f.id));for(const n of state.notes)if(!ids.has(n.folderId))n.folderId=null;if(!['all','unfiled'].includes(state.selectedFolder)&&!ids.has(state.selectedFolder))state.selectedFolder='all';}
function noteInFolder(note){return state.selectedFolder==='all'||(state.selectedFolder==='unfiled'?!note.folderId:note.folderId===state.selectedFolder);}
function selectFolder(id){selectedNotes.clear();selectionAnchor=null;state.selectedFolder=id;persist();list();}
function renderFolders(){const nav=$('folders');nav.replaceChildren();const items=[{id:'all',name:folderText('All notes','全部笔记')},{id:'unfiled',name:folderText('Unfiled','未分类')},...state.folders];for(const f of items){const row=document.createElement('div');row.className='folder-row';const button=document.createElement('button');button.className='folder-button'+(f.id===state.selectedFolder?' active':'');button.dataset.folderId=f.id;button.setAttribute('aria-pressed',String(f.id===state.selectedFolder));const name=document.createElement('span');name.textContent=f.name;const count=document.createElement('small');count.textContent=state.notes.filter(n=>f.id==='all'||(f.id==='unfiled'?!n.folderId:n.folderId===f.id)).length;button.append(name,count);button.onclick=()=>selectFolder(f.id);row.append(button);if(!['all','unfiled'].includes(f.id)){const action=document.createElement('button');action.className='folder-more';action.textContent='⋯';action.setAttribute('aria-label',folderText('Manage folder ','管理文件夹 ')+f.name);action.onclick=e=>openFolderMenu(f,e.currentTarget);row.append(action)}nav.append(row)}}
function newFolder(){const raw=prompt(folderText('Folder name (up to 60 characters):','文件夹名称（最多 60 个字）：'));if(raw===null)return;const name=raw.trim();if(!name||name.length>60){alert(folderText('Enter a name with 1–60 characters.','请输入 1–60 个字的名称。'));return;}if(state.folders.some(f=>f.name.toLowerCase()===name.toLowerCase())){alert(folderText('A folder with this name already exists.','已经有同名文件夹了。'));return;}const f={id:folderId(),name};state.folders.push(f);selectFolder(f.id);}
let folderMenuId=null;
function closeFolderMenu(){$('folder-menu').hidden=true;folderMenuId=null;}
function openFolderMenu(folder,origin){closeNoteMenu();folderMenuId=folder.id;const menu=$('folder-menu');menu.hidden=false;const r=origin.getBoundingClientRect();menu.style.left=Math.max(8,Math.min(r.left,innerWidth-menu.offsetWidth-8))+'px';menu.style.top=Math.max(8,Math.min(r.bottom,innerHeight-menu.offsetHeight-8))+'px';$('rename-folder').focus();}
function populateMoveMenu(note){const select=$('move-folder');select.replaceChildren();for(const f of [{id:'',name:folderText('Unfiled','未分类')},...state.folders]){const option=document.createElement('option');option.value=f.id;option.textContent=f.name;select.append(option)}select.value=note.folderId||'';}
function setupFolders(){normalizeFolders();const panel=document.createElement('section');panel.className='folder-panel';const heading=document.createElement('div');heading.className='folder-heading';const text=document.createElement('span');text.textContent=folderText('Folders','文件夹');const add=document.createElement('button');add.id='new-folder';add.textContent='＋';add.title=folderText('New folder','新建文件夹');add.setAttribute('aria-label',add.title);add.onclick=newFolder;heading.append(text,add);const nav=document.createElement('nav');nav.id='folders';nav.setAttribute('aria-label',text.textContent);panel.append(heading,nav);$('search').before(panel);
 const label=document.createElement('label');label.className='move-label';label.textContent=folderText('Move to folder','移到文件夹');const select=document.createElement('select');select.id='move-folder';select.setAttribute('aria-label',label.textContent);label.append(select);$('note-menu').append(label);select.onchange=()=>{const note=state.notes.find(n=>n.id===contextId);if(!note)return;note.folderId=select.value||null;persist();list();};
 const menu=document.createElement('div');menu.id='folder-menu';menu.className='note-menu';menu.hidden=true;menu.setAttribute('role','menu');for(const [id,en,zh] of [['rename-folder','Rename folder','重命名文件夹'],['delete-folder','Delete folder','删除文件夹']]){const b=document.createElement('button');b.id=id;b.textContent=folderText(en,zh);b.setAttribute('role','menuitem');menu.append(b)}document.body.append(menu);
 $('rename-folder').onclick=()=>{const f=state.folders.find(f=>f.id===folderMenuId);closeFolderMenu();if(!f)return;const raw=prompt(folderText('Folder name:','文件夹名称：'),f.name);if(raw===null)return;const name=raw.trim();if(!name||name.length>60){alert(folderText('Enter a name with 1–60 characters.','请输入 1–60 个字的名称。'));return;}if(state.folders.some(other=>other.id!==f.id&&other.name.toLowerCase()===name.toLowerCase())){alert(folderText('A folder with this name already exists.','已经有同名文件夹了。'));return;}f.name=name;persist();list();};
 $('delete-folder').onclick=()=>{const f=state.folders.find(f=>f.id===folderMenuId);closeFolderMenu();if(!f||!confirm(folderText('Delete folder “'+f.name+'”? Its notes will move to Unfiled.','删除文件夹“'+f.name+'”？里面的笔记会移到未分类，不会删除。')))return;state.folders=state.folders.filter(other=>other.id!==f.id);for(const n of state.notes)if(n.folderId===f.id)n.folderId=null;if(state.selectedFolder===f.id)state.selectedFolder='unfiled';persist();list();};
 document.addEventListener('pointerdown',e=>{if(!menu.hidden&&!menu.contains(e.target))closeFolderMenu()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeFolderMenu()});window.addEventListener('resize',closeFolderMenu);nav.addEventListener('scroll',closeFolderMenu);
 setupNoteDragging();renderFolders();}

const selectedNotes=new Set();let selectionAnchor=null,draggedNotes=[];
function paintNoteSelection(){for(const button of $('notes').querySelectorAll('.note')){button.draggable=true;button.classList.toggle('selected',selectedNotes.has(button.dataset.noteId));button.title=folderText('Drag to a folder · Ctrl / Shift to select multiple','拖到文件夹 · Ctrl / Shift 多选');}}
function clearDragHighlights(){for(const button of $('folders').querySelectorAll('.drop-target'))button.classList.remove('drop-target');}
function setupNoteDragging(){const notes=$('notes'),folders=$('folders');
 new MutationObserver(paintNoteSelection).observe(notes,{childList:true});
 notes.addEventListener('click',e=>{const button=e.target.closest('.note');if(!button)return;const id=button.dataset.noteId;closeNoteMenu();if(e.ctrlKey||e.metaKey||e.shiftKey){e.preventDefault();e.stopPropagation();const visible=[...notes.querySelectorAll('.note')].map(b=>b.dataset.noteId);if(e.shiftKey&&selectionAnchor&&visible.includes(selectionAnchor)){const a=visible.indexOf(selectionAnchor),b=visible.indexOf(id);if(!e.ctrlKey&&!e.metaKey)selectedNotes.clear();for(const selected of visible.slice(Math.min(a,b),Math.max(a,b)+1))selectedNotes.add(selected);}else{selectedNotes.has(id)?selectedNotes.delete(id):selectedNotes.add(id);selectionAnchor=id;}paintNoteSelection();return;}selectedNotes.clear();selectionAnchor=id;paintNoteSelection();},true);
 notes.addEventListener('dragstart',e=>{const button=e.target.closest('.note');if(!button||!e.dataTransfer)return;const id=button.dataset.noteId;if(!selectedNotes.has(id)){selectedNotes.clear();selectedNotes.add(id);selectionAnchor=id;}const visible=new Set([...notes.querySelectorAll('.note')].map(b=>b.dataset.noteId));draggedNotes=[...selectedNotes].filter(id=>visible.has(id));e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('application/x-nnotepad-notes',JSON.stringify(draggedNotes));e.dataTransfer.setData('text/plain',draggedNotes.length+' '+folderText('notes','篇笔记'));paintNoteSelection();closeNoteMenu();closeFolderMenu();});
 notes.addEventListener('dragend',()=>{draggedNotes=[];clearDragHighlights()});
 folders.addEventListener('dragover',e=>{const button=e.target.closest('.folder-button');if(!button||button.dataset.folderId==='all'||!draggedNotes.length)return;e.preventDefault();e.dataTransfer.dropEffect='move';clearDragHighlights();button.classList.add('drop-target');});
 folders.addEventListener('dragleave',e=>{const button=e.target.closest('.folder-button');if(button&&!button.contains(e.relatedTarget))button.classList.remove('drop-target');});
 folders.addEventListener('drop',e=>{const button=e.target.closest('.folder-button');if(!button||!draggedNotes.length)return;e.preventDefault();const target=button.dataset.folderId;if(target!=='unfiled'&&!state.folders.some(f=>f.id===target))return;const ids=new Set(draggedNotes);for(const note of state.notes)if(ids.has(note.id))note.folderId=target==='unfiled'?null:target;draggedNotes=[];selectedNotes.clear();clearDragHighlights();persist();list();});
 document.addEventListener('keydown',e=>{if(e.key==='Escape'){selectedNotes.clear();paintNoteSelection();}});
}
